steps:

  # Install dependenies and run tests
  - name: "python"
    entrypoint: 'bash'
    args: ['./scripts/install-dependencies.sh', '&&', './scripts/test-app.sh']

  # Docker build
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args: ['./scripts/build-image.sh']
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'LOCATION=${LOCATION}'
      - 'REPO_NAME=${REPO_NAME}'

  # Docker push to Artifact Registry
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: 'bash'
    args: ['./scripts/check-artifact-registry-repo-or-create-one.sh', '&&', '.scripts/push-image.sh']
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'LOCATION=${LOCATION}'
      - 'REPO_NAME=${REPO_NAME}'

images:
- '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${REPO_NAME}:latest'
