steps:

  - name: "python"
    entrypoint: 'bash'
    args: ['./scripts/install_dependencies.sh', '&&', './scripts/test_app.sh']

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args: ['./scripts/build_docker.sh']
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'LOCATION=${LOCATION}'
      - 'REPO_NAME=${REPO_NAME}'
