apiVersion: v1
kind: Service
metadata:
  name: cd-pipeline-spinnaker-and-gke-service
spec:
  selector:
    app: cd-pipeline-spinnaker-and-gke-service
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
